-- <nixCats>/lua/keymapConf/picker.lua
-- <Leader>p: Fuzzy finder picker
local snacks_keymap = require("lzextras").keymap("snacks.nvim")

-- Picker picker
snacks_keymap.set("n", "<Leader>p<Leader>", function()
  require("snacks").picker()
end, { desc = "Picker picker" })
-- Resume last picker
snacks_keymap.set("n", "<Leader>pp", function()
  require("snacks").picker.resume()
end, { desc = "Picker picker" })

-- Grep search
snacks_keymap.set("n", "<Leader>p/", function()
  require("snacks").picker.grep()
end, { desc = "Grep search" })
snacks_keymap.set("n", "<Leader>pb", function()
  require("snacks").picker.lines()
end, { desc = "Lines in buffer" })
snacks_keymap.set("n", "<Leader>pB", function()
  require("snacks").picker.grep_buffers()
end, { desc = "Grep open buffers" })
snacks_keymap.set({ "n", "x" }, "<Leader>pw", function()
  require("snacks").picker.grep_word()
end, { desc = "Visual selection or word" })

-- Other searches
snacks_keymap.set("n", '<Leader>p"', function()
  require("snacks").picker.registers()
end, { desc = "Registers" })
snacks_keymap.set("n", "<Leader>p?", function()
  require("snacks").picker.search_history()
end, { desc = "Search history" })
snacks_keymap.set("n", "<Leader>pa", function()
  require("snacks").picker.autocmds()
end, { desc = "Nvim Autocmds" })
snacks_keymap.set("n", "<Leader>pc", function()
  require("snacks").picker.command_history()
end, { desc = "Command history" })
snacks_keymap.set("n", "<Leader>pC", function()
  require("snacks").picker.commands()
end, { desc = "Commands" })
snacks_keymap.set("n", "<Leader>pd", function()
  require("snacks").picker.diagnostics()
end, { desc = "Diagnostics" })
snacks_keymap.set("n", "<Leader>pD", function()
  require("snacks").picker.diagnostics_buffer()
end, { desc = "Diagnostics in buffer" })
snacks_keymap.set("n", "<Leader>ph", function()
  require("snacks").picker.help()
end, { desc = "Help pages" })
snacks_keymap.set("n", "<Leader>pH", function()
  require("snacks").picker.highlights()
end, { desc = "Highlights" })
snacks_keymap.set("n", "<Leader>pi", function()
  require("snacks").picker.icons()
end, { desc = "Icons" })
snacks_keymap.set("n", "<Leader>pj", function()
  require("snacks").picker.jumps()
end, { desc = "Jumps" })
snacks_keymap.set("n", "<Leader>pk", function()
  require("snacks").picker.keymaps()
end, { desc = "Keymaps" })
snacks_keymap.set("n", "<Leader>pl", function()
  require("snacks").picker.loclist()
end, { desc = "Location list" })
snacks_keymap.set("n", "<Leader>pm", function()
  require("snacks").picker.marks()
end, { desc = "Marks" })
snacks_keymap.set("n", "<Leader>pM", function()
  require("snacks").picker.man()
end, { desc = "Man pages" })
snacks_keymap.set("n", "<Leader>pq", function()
  require("snacks").picker.qflist()
end, { desc = "Quickfix list" })
snacks_keymap.set("n", "<Leader>pu", function()
  require("snacks").picker.undo()
end, { desc = "Undo history" })
